---
- hosts: all
  sudo: yes 
  user: ubuntu

  tasks:

    - name: Update the source via git
      sudo: no
      shell: git pull
      when: vcs == "git"
      sudo: no
      args:
           chdir: "{{ sites_dir }}/{{ project_dir }}"
      tags:
            - vcs 

    - name: Put the site into maint mode
      shell: cp "pages/templates/offline.html" static
      args:
           chdir: "{{ sites_dir }}/{{ project_dir }}"
      tags:
            - start_maint 

    - name: Install/update apps required by the Django app inside virtualenv
      pip: virtualenv={{ virtualenvs_dir }}/{{ project_name }}-env 
        requirements={{ sites_dir }}/{{ project_dir }}/requirements/production.txt
      tags:
           - django

    - name: Run Django South migrations
      shell: . {{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate
            && python manage.py migrate --noinput --settings=wagtail_cookie.settings.production
      environment: django_env
      sudo: no
      args:
           chdir: "{{ sites_dir }}/{{ project_dir }}"
      tags:
            - django

#    - name: Load Initial Data
#      shell: . {{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate
#                && python manage.py load_initial_data
#      environment: django_env
#      sudo: no
#      args:
#          chdir: "{{ sites_dir }}/{{ project_dir }}"
#          tags:
#                - django

    - name: Run Django collectstatic
      shell: . {{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate
            && python manage.py collectstatic --noinput --settings=wagtail_cookie.settings.production
      environment: django_env
      sudo: no
      args:
          chdir: "{{ sites_dir }}/{{ project_dir }}"
      tags:
         - django

    - name: Run Django compress
      shell: . {{ virtualenvs_dir }}/{{ project_name }}-env/bin/activate
             && python manage.py compress --settings=wagtail_cookie.settings.production
      environment: django_env
      sudo: no
      args:
           chdir: "{{ sites_dir }}/{{ project_dir }}"
      tags:
           - django

    - name: Take the site out of  maint mode
      shell: rm static/offline.html
      args:
           chdir: "{{ sites_dir }}/{{ project_dir }}"
      tags:
           - django
           - end_maint

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart circus
      service: name=circus state=restarted