---
- name: update the apt-cache
  apt: update_cache=yes  cache_valid_time=36000
  tags:
      - cache 
      - packages 

- name: install common package dependencies
  apt: >
        pkg={{ item }}  
        state=latest
        force=yes
  with_items:
    - aptitude
    - build-essential
    - bash
    - openssl
    - libssl-dev
    - git
    - supervisor
    - ufw
    - fail2ban
  tags:
      - packages 

- name: safe upgrade 
  apt: upgrade=safe force=yes
  tags:
      - upgrade 
      - packages
